(() => {
'use strict';
const root=document.getElementById('screen');let step=0,busy=false,sent=false,quick=false;
if(new URLSearchParams(location.search).get('embed')==='1')document.body.classList.add('embed');
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('embed'))parent.postMessage({type:'bc-help-close'},location.origin);});
const a=window.bcHelpAnalytics;const state={symptom:'',impact:'',started:'',detail:'',changes:'',equipment:'',site:'',name:'',company:'',email:'',phone:'',website:''};let leadId=a.leadId();let pending=null;
const symptoms=['Vacuum / pumpdown trouble','Heating / temperature trouble','Cooling / quench trouble','Controls / unexpected shutdown','Mechanical trouble','Something else / not sure'];
const impacts=['Equipment is down','Production is reduced','Problem comes and goes','Still running; concerned'];
const prompts={
'Vacuum / pumpdown trouble':'What is different from normal? If you already have a pressure reading or alarm, include it with units.',
'Heating / temperature trouble':'Does it fail to heat, heat slowly, or miss the target? Include any displayed alarm.',
'Cooling / quench trouble':'What changed during cooling? Include any displayed alarm or reading you already have.',
'Controls / unexpected shutdown':'What does the screen say, and when in the cycle does it happen?',
'Mechanical trouble':'Where is the problem, and what do you notice?',
'Something else / not sure':'Describe what you notice in your own words.'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const choices=(name,items)=>`<div class="choices">${items.map(x=>`<label class="choice"><input required type="radio" name="${name}" value="${esc(x)}" ${state[name]===x?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div>`;
const field=(name,label,placeholder='',type='text',required=false)=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(state[name])}" placeholder="${esc(placeholder)}" maxlength="${name==='email'?254:160}" ${required?'required':''}></label>`;
const area=(name,label,placeholder,required=false)=>`<label class="field">${label}<textarea name="${name}" maxlength="2000" placeholder="${esc(placeholder)}" ${required?'required':''}>${esc(state[name])}</textarea></label>`;
function collect(){root.querySelectorAll('input,textarea,select').forEach(el=>{if(el.type!=='radio'||el.checked)state[el.name]=el.value;});}
function brief(){return [['Concern',state.symptom],['Production impact',state.impact],['First noticed',state.started||'Not yet specified'],['What is happening',state.detail||'To discuss with the team'],['Recent changes / work already attempted',state.changes||'Not yet specified'],['Equipment',state.equipment||'To be identified'],['Facility / location',state.site||'To be confirmed']];}
function briefText(){return 'BEAR & CROC | EQUIPMENT PROBLEM BRIEF\nCustomer-reported information\n\n'+brief().map(([k,v])=>k+': '+v).join('\n\n');}
function status(msg,error=false){const s=document.getElementById('status');s.textContent=msg;s.className='status '+(error?'error':'');}
function render(){
 document.getElementById('step-label').textContent=`Step ${step+1} of 3`;document.querySelectorAll('#steps li').forEach((el,i)=>el.classList.toggle('active',i===step));
 if(step===0){root.innerHTML=`<form id="flow"><h2 tabindex="-1">What’s happening?</h2><p class="hint">Choose the closest match. We’ll help with the details.</p><fieldset><legend class="quiet">Main concern</legend>${choices('symptom',symptoms)}</fieldset><fieldset><legend>How is it affecting production?</legend>${choices('impact',impacts)}</fieldset><div class="actions"><button type="button" id="quick">Just describe it</button><button class="primary">Add a little context →</button></div></form>`;}
 if(step===1){root.innerHTML=`<form id="flow"><h2 tabindex="-1">${quick?'Tell us what’s happening.':'What have you noticed?'}</h2><p class="hint">${quick?'Start with a sentence. We can sort out the category with you.':'A sentence is enough. Any unknowns can wait for the conversation.'}</p>${area('detail',quick?'What is the equipment doing?':prompts[state.symptom],'For example: the last three cycles have taken longer than usual.',quick)}${field('started','When did it start? <small>Optional</small>','Today, last week, after a repair…')}${area('changes','Anything changed or already tried? <small>Optional</small>','Recent service, a different load, a recurring alarm…')}<div class="pair">${field('equipment','Equipment <small>Optional</small>','Make, model or shop tag')}${field('site','Location <small>Optional</small>','Facility / city / state')}</div><div class="actions"><button type="button" id="back">Back</button><button class="primary">See my problem brief →</button></div></form>`;}
 if(step===2){root.innerHTML=`<h2 tabindex="-1">Your problem, in one place.</h2><p class="hint">Ready to share with your team or send to ours.</p><div class="brief"><p class="eyebrow">EQUIPMENT PROBLEM BRIEF</p><p class="quiet">Customer-reported information</p><dl>${brief().map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl></div><div class="actions"><button id="back">Edit details</button><button id="save">Save brief</button><button id="print">Print / PDF</button></div><div class="contact"><h3>Want Bear & Croc to help?</h3><p>Send this brief so we can follow up about the next step. You don’t need to repeat the story.</p><form id="send"><div class="pair">${field('name','Your name','','text',true)}${field('email','Email','','email',true)}${field('company','Company <small>Optional</small>')}${field('phone','Phone <small>Optional</small>','','tel')}</div><label class="trap" aria-hidden="true">Leave blank<input name="website" tabindex="-1" autocomplete="off"></label><button class="primary" id="send-button">Send to Bear & Croc</button><p class="quiet">Submitting requests follow-up; it does not book a visit or confirm a response time. Photos and records can follow by email.</p></form><p id="status" role="status" aria-live="polite"></p></div>`;
 document.getElementById('save').onclick=()=>{const u=URL.createObjectURL(new Blob([briefText()],{type:'text/plain;charset=utf-8'}));const el=document.createElement('a');el.href=u;el.download='equipment-problem-brief.txt';el.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};document.getElementById('print').onclick=()=>window.print();document.getElementById('send').onsubmit=send;
 }
 const flow=document.getElementById('flow');if(flow)flow.onsubmit=e=>{e.preventDefault();collect();if(step===0)quick=false;step++;render();focusHeading();};const back=document.getElementById('back');if(back)back.onclick=()=>{if(busy)return;collect();if(sent){sent=false;leadId=a.leadId();pending=null;}step--;render();focusHeading();};const quickButton=document.getElementById('quick');if(quickButton)quickButton.onclick=()=>{quick=true;state.symptom='Something else / not sure';state.impact='Not yet specified';step=1;render();focusHeading();};
}
function focusHeading(){root.querySelector('h2').focus();document.querySelector('.surface').scrollIntoView({block:'start',behavior:'smooth'});}
async function send(e){e.preventDefault();if(busy||sent)return;collect();const payload={kind:'reactive',name:state.name,email:state.email,company:state.company,phone:state.phone,website:state.website,problem:{symptom:state.symptom,impact:state.impact,started:state.started,detail:state.detail,changes:state.changes,equipment:state.equipment,site:state.site},attribution:a.attribution()};
 const fingerprint=JSON.stringify(payload);if(pending&&pending!==fingerprint)leadId=a.leadId();pending=fingerprint;payload.leadId=leadId;busy=true;document.getElementById('back').disabled=true;const button=document.getElementById('send-button');button.disabled=true;button.textContent='Sending…';status('Sending your brief…');
 try{const res=await fetch('../submit-assessment.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok||!data.ok)throw Error();sent=true;document.getElementById('send').hidden=true;status('Your brief has been sent to Bear & Croc. Our team will follow up using the contact details you provided. Reference: '+leadId);a.track('generate_lead',{form_name:'equipment_problem',lead_id:leadId});}
 catch{status('We couldn’t confirm the send. Try again, or save your brief and email it to sales@bearandcroc.com. Your details are still here.',true);button.disabled=false;button.textContent='Try sending again';}finally{busy=false;document.getElementById('back').disabled=false;}
}
render();
})();
